[package]
name = "base58"
version = "0.1.0"
authors = ["Hatter Jiang@Pixelbook <jht5945@gmail.com>"]
edition = "2018"

[dependencies]
num = "*"
argparse = "0.2.2"
rust_util = "0.6.3"

[dev-dependencies]
rand = "*"
