[package]
name = "base58"
version = "0.1.0"
authors = ["Hatter Jiang@Pixelbook <jht5945@gmail.com>"]
edition = "2018"

[dependencies]
num = "*"
term = "0.5.2"
argparse = "0.2.2"

[dev-dependencies]
rand = "*"
